### ISSUE TITLE
Show tags option causing misalignment in placement of entity category labels

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/NERVE#16]
![screenshot 2017-05-10 11 03 18](https://user-images.githubusercontent.com/545952/26941798-c442ae0e-4c4d-11e7-8329-a0fa1f1e9cb2.png)

**Comment by Thaerious** [comment]
Show tags has now been changed to "Tag Mode" / "Overlay Mode" tag mode was never supposed to have overlay tags on it.  This has been fixed.
