### ISSUE TITLE
Internal/interim tags being retained when document is saved/downloaded: document invalid

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/NERVE#17]
Used NERVE 1.5.1a

Document is not even well formed: looks like all the internal tags are retained. See excerpt below.

Input file: https://www.dropbox.com/s/cdlovsp4nckjq8t/NERVE_CWRC_entry_schema_test_entry_SHORT_NO_ENTITY_TAGS.xml?dl=0
Output file: https://www.dropbox.com/s/zmz25j0vx6bczog/NERVE_processed_CWRC_entry_schema_test_entry_SHORT_NO_ENTITY_TAGS.xml?dl=0

Best I could do is a screenshot as I couldn't paste the markup.

![image](https://user-images.githubusercontent.com/545952/26942544-73ae2772-4c50-11e7-8187-a48eea6a7178.png)

**Comment by Thaerious** [comment]
This is now fixed.
