### ISSUE TITLE
Tagging from the Action menu not working

### ISSUE THREAD

**Issue by ilovan** [cwrc/NERVE#21]
Tested with multiple files in Chrome:

1. Load document
2. Select string of text
3. Click on Action>Tag
    - selection disappears
    - no entity is added

If instead of No. 3 I click on Ctr+E: 
    - new entity tag is created (entity type identical with the type selected in the right hand panel)

**Comment by Thaerious** [comment]
The 'default' css setting for text select may have changed, it was no longer enabling where I wanted it to, so I enabled it for the whole document.  This inadvertently caused the document to unselect when the menu is clicked.  I have now specified 'text' select on the elements I want to allow selection and 'none' on the body (all others).  This should fix the issue.

**Comment by ilovan** [comment]
It works in Chrome now, but not in Firefox.

**Comment by Thaerious** [comment]
I don't do any checking in firefox, chrome is the only target platform.

**Comment by ilovan** [comment]
fixed
