### ISSUE TITLE
NERVE dictionaries: improve recognition

### ISSUE THREAD

**Issue by ilovan** [cwrc/NERVE#23]
Issue pulled out from https://github.com/cwrc/NERVE/issues/19

Is there a way to populate the dictionaries  with the collections of CWRC entities , as a starting point?

I am asking because at this point (and for early adoption of the tool), the better part of the entities, when  they are not tagged in XML, are not recognised at all or are wrongly identified as a place entity (Ed explains why this is so in the issue mentioned above)

Correct me if I am wrong, @Thaerious , but NERVE is using the Stanford NER at its basis. 
I took the same text and ran it through both NERVE and the online Standford NER demo at http://nlp.stanford.edu:8080/ner/

The Standford NER demo is by far more accurate in identifying the entities in the fragment:
![capture](https://user-images.githubusercontent.com/6600070/33396190-0697f97c-d505-11e7-9258-83edeab0726f.PNG)

By contrast, this is the same fragment in NERVE:
![capture1](https://user-images.githubusercontent.com/6600070/33396352-7b0b4124-d505-11e7-8b9a-c6e91bf0cca4.PNG)

Having the CWRC entity collections added as custom dictionaries seems preferable to me, but if that doesn't work or is too complicated, can we restore/install the dictionaries that the default Standford NER uses?

**Comment by Thaerious** [comment]
Yes it is fairly simple to populate the dictionary, it's a no-frills mysql database.  It's tagging this way because I've only populated it with geonames to make sure it works.  There is also the posssibility of changing the order of tagging precedence so Stanford gets used before the dictionary.

**Comment by Thaerious** [comment]
I have now reversed the order of taggers, so it's now: NER, DICTIONARY.  I have also added a dictionary lookup to NER tags if the link is not set.  Previously all entities that were tagged in previous steps were ingnored by later steps.

**Comment by ilovan** [comment]
Recognition is improved, so closing this issue with the understanding that this is not the same as:

(1) User choice of specific dictionaries (2 days)
(2) Incorporate CWRC and Orlando Entities into the dictionaries/whitelists (1 day)

being fulfilled
