### ISSUE TITLE
CWRC, VIAF and Geonames lookups don't work , despite being logged in 

### ISSUE THREAD

**Issue by ilovan** [cwrc/NERVE#24]
Tested with person, organisation, place and title. 
This may be something we don't want to fix just now if we go ahead with swapping the old lookups with the new ones.

**Comment by Thaerious** [comment]
Could not reproduce.  Can you double check that this is occuring and that you are logged in to http://beta.cwrc.ca

**Comment by ilovan** [comment]
This was about the old dialogs, so will close for now
