### ISSUE TITLE
Entity labels inconsistent

### ISSUE THREAD

**Issue by ilovan** [cwrc/NERVE#25]
Sometimes missing, sometimes offset from the tagged entity, always disappearing if you switch to tag mode and back to overlay mode.

**Comment by Thaerious** [comment]
Seems to be an intermittent issue, I'll check back on this one later.

**Comment by ilovan** [comment]
The offset and missing part seem to be fixed now. Could not verify the "tags on/off" portion because https://github.com/cwrc/NERVE/issues/67

**Comment by ilovan** [comment]
verified now. labels seem much more consistent.
