### ISSUE TITLE
Saving gets stuck on "Connecting Scriber Socket"

### ISSUE THREAD

**Issue by ilovan** [cwrc/NERVE#26]
1. Uploaded https://www.dropbox.com/s/qfjdkpza4c0dd9m/NERVE_TEI_test_file_short_NO_entity_tags.xml?dl=0
2. Removed a few entity tags 
3. Added others
4. Linked some to Google Geocode ( the only entity lookup service that is currently working)
5. Tried to save - got stuck on "Connecting Scriber Socket"

**Comment by Thaerious** [comment]
I can not reproduce this error, if you were having network connectivity issues then you may not have been able to connect to the server.  Let me know if this happens again / predictably.

**Comment by ilovan** [comment]
can't reproduce anymore. will close
