### ISSUE TITLE
Unable to load a CWRC schema object

### ISSUE THREAD

**Issue by ilovan** [cwrc/NERVE#40]
<img width="1415" alt="screen shot 2018-02-12 at 2 45 08 pm" src="https://user-images.githubusercontent.com/6600070/36121440-670cc31c-1003-11e8-81a6-efd00157851b.png">

This is the document I was trying to upload: https://www.dropbox.com/s/0mk2f1kak99m851/Kemp%2C%20Penn%20%2832%29%20vdL7.xml?dl=0

**Comment by Thaerious** [comment]
Offending line "<?oxy_comment_start author="leslieallin" timestamp="20161209T164737-0500" comment="ask"?>" is a processing instruction.  I don't believe the parser is handling them at this moment.  I'll have to open it up and add this.  See: http://www.jelks.nu/XML/xmlebnf.html#NT-XMLDecl

**Comment by Thaerious** [comment]
I have added an antlr rule to recognize isntruction nodes within the document as opposed to just the start of the document.

**Comment by ilovan** [comment]
Seems to be fixed now so I will close.
