### ISSUE TITLE
HTML div artifacts being left behind.

### ISSUE THREAD

**Issue by ilovan** [cwrc/NERVE#41]
See the title tag in the header (all children and attributes added by NERVE)

[TEI - edit mode.pdf](https://github.com/cwrc/NERVE/files/1831163/TEI.-.edit.mode.pdf)

**Comment by Thaerious** [comment]
Prev title:  Edit mode, which should not automatically change the document in any way, takes existing title/person/org/place tags and edits them to fit the NERVE structure for entities.

**Comment by ilovan** [comment]
fixed
