### ISSUE TITLE
Add Copy to the Action menu

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/NERVE#5]

**Comment by SusanBrown** [comment]
I realize that it is complicated and it won't be possible to explain how to use it, but this at least would flag that it is possible.

**Comment by SusanBrown** [comment]
By Copy I mean the functionality whereby you select a bunch of entities and copy the values (standard label and link, if any) associated with another entity to all those entities. 

I think it should be flagged in the menu to show it exists although it is pretty complicated (I can't recall how to to it, so if you could lay it out in the [draft documentation document](https://docs.google.com/document/d/112lBElcjSjllteLoR3y91Zk7y9VMmFBjSshaAL5oBIU/edit#) that would be very helpful), so I was just saying that it wouldn't be intuitive to do.

Maybe it should be something longer like Copy Entities or Copy Entity Values for clarity.

**Comment by Thaerious** [comment]
It is now copy and paste.
