### ISSUE TITLE
When using NERVE in NER & linking mode, nested tags are created

### ISSUE THREAD

**Issue by ilovan** [cwrc/NERVE#51]
<placeName ref="" key="Paris">
               <div class="tagname-markup" data-norm="PLACE">placeName</div>
               <div class="contents">
                  <placename key="Paris, France" ref="www.geonames.org/2988507">Paris</placename>
               </div>
            </placeName>

**Comment by Thaerious** [comment]
Could you see if this is still occuring, I believe it has been fixed.

**Comment by ilovan** [comment]
nope. still there:

same files as referenced in https://github.com/cwrc/NERVE/issues/61
![image](https://user-images.githubusercontent.com/6600070/41047086-0432963a-6969-11e8-85ef-593a6ed2cd44.png)

**Comment by Thaerious** [comment]
Please link to the file and describe which open command you are using, I still can not recreate this.

**Comment by ilovan** [comment]
1. File > Open - NER & Link
2. Uploaded:
https://www.dropbox.com/s/47obkh11xv1m8td/NERVE%20-%20ultra-basic%20test%20-%20TEI.xml?dl=0
3. File > Save
Resulting file:
https://www.dropbox.com/s/itlnh01dc45esab/NERVE%20-%20ultra-basic%20test%20-%20TEI%20-%20after.xml?dl=0

**Comment by Thaerious** [comment]
Try it on 0.8.6 and see if it still happens.  It's still not reproducing for me.  May have to wait till our next meeting so you can show me it happening.

**Comment by ilovan** [comment]
DOesn't happen anymore in TEI documents (could not test with Orlando or CWRC Documents because  the NER doesn't seem to work on those document types https://github.com/cwrc/NERVE/issues/69)
