### ISSUE TITLE
Ctrl Z wipes out entity panel

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/NERVE#53]
Tried to undo an entity I had tagged using Ctrl Z for "undo".
Using Chrome on a Mac

Top portion with buttons for orgname, date etc but all entities disappeared from the list below.

**Comment by SusanBrown** [comment]
Reloading the page restores the panel but the entity tagging and linking done before the glitch has been lost.

**Comment by ilovan** [comment]
confirmed. will close
