### ISSUE TITLE
Fix line breaks caused by soft line breaks inserted by Oxygen

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/NERVE#6]
I just cleaned the same document of all Oxygen soft returns and indents (please find attached) and reloaded this new version of the document in both NERVE and CWRC-Writer. Since both read the same cwrc TEI css, the layout should be identical, but it's not.

This is the CWRC-Writer test object: http://beta.cwrc.ca/islandora/object/cwrc%3Ab8939f93-7a08-44df-b124-d35fc78161b5#cwrc:b8939f93-7a08-44df-b124-d35fc78161b5

**Comment by Thaerious** [comment]
I'm not sure what you're getting at here.  What program is inserting soft returns and indents?

**Comment by susanirenebrown** [comment]
This relates to the long email thread in which Mihaela established that files that had been opened in Oxygen were being interpreted by NERVE as having line breaks where there were none. If you cannot find the email thread let me know and I’ll resend it to you.

**Comment by ilovan** [comment]
The line-break conversation that Susan was talking about took place 10-14 March of this year (subject: NERVE)

@Thaerious , did you actively do anything about this? It doesn't seem to be an issue anymore.
