### ISSUE TITLE
Some entity tags added twice

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/NERVE#62]
Before and after files:
https://www.dropbox.com/s/zpw4czrckjyl1u2/NERVE%20-%20ultra-basic%20test%20-%20TEI.xml?dl=0
https://www.dropbox.com/s/gsc670mjb18a1rr/NERVE%20-%20ultra-basic%20test%20-%20TEI%20%285%29.xml?dl=0

**Comment by Thaerious** [comment]
Issue fixed in 0.8.5 (http://dh.sharcnet.ca/NERVE-0.8.5/nerve.html).

**Comment by ilovan** [comment]
Confirmed fixed. Will close
