### ISSUE TITLE
Clicking on an entity in the left hand panel is inconsistent in populating the right hand panel

### ISSUE THREAD

**Issue by ilovan** [cwrc/NERVE#65]
Tested on https://www.dropbox.com/s/x5ejmpfbs5fcvxd/NERVE_CWRC_entry_schema_test_entry_LONG_WITH_ENTITY_TAGS.xml?dl=0

![jun-06-2018 08-26-41](https://user-images.githubusercontent.com/6600070/41044493-9de8c944-6963-11e8-86f9-a4e2644eb932.gif)

**Comment by Thaerious** [comment]
That gif is rather small, could you describe what you mean by inconsistent.

**Comment by ilovan** [comment]
I think you can see even from the small giff that clicking on some entities in the list populates the right-hand panel, while clicking on others turns the panel blank.
That was the behavior when tested on a Mac in Chrome using 8.6

I just tested again, with the same document, on a PC, using Chrome and 8.7:
This time around, clicking on some entities turned the content of the right hand panel pink. (entities where this is visible: The Canadian MOnthly and National Review, New Orleans.

Document open in NER  & link mode.

**Comment by Thaerious** [comment]
It should retain the values of the last entity clicked.  If you press ctrl while clicking then you can select multiple entities.  If one or more of the selected entities has a different value than the background of said value will be pink.

**Comment by ilovan** [comment]
this looks like it's fixed now. I'll close it.
