### ISSUE TITLE
Content of entity list persists even if user closes current file and/or opens another file 

### ISSUE THREAD

**Issue by ilovan** [cwrc/NERVE#66]
![image](https://user-images.githubusercontent.com/6600070/41045228-3485946c-6965-11e8-8e9c-dd7ed4273d88.png)
![image](https://user-images.githubusercontent.com/6600070/41045259-46c2c000-6965-11e8-877e-256e40fc08b1.png)

Only refreshing the page clears and refreshes it:

![image](https://user-images.githubusercontent.com/6600070/41045306-6148f0b6-6965-11e8-9968-63d6eb882160.png)

**Comment by ilovan** [comment]
if user hits the refresh button, the list is refreshed to reflect the entities in the current text

**Comment by Thaerious** [comment]
Should be fixed with the next push.

**Comment by ilovan** [comment]
Confirmed fixed on http://dh.sharcnet.ca/NERVE-0.8.7/nerve.html
