### ISSUE TITLE
Once you turn tags on, you can't turn them off. 

### ISSUE THREAD

**Issue by ilovan** [cwrc/NERVE#67]
Tested on Chrome, with multiple files. 
You have to refresh the page to get the tags to disappear.

**Comment by Thaerious** [comment]
Fixed, will no longer maintain mode when page is refreshed.

**Comment by ilovan** [comment]
What version of NERVE should I test this on?
http://dh.sharcnet.ca/NERVE-0.8.5/nerve.html
is still exhibiting the same issue. 

I used the menu options, not the browser page refresh

1. Pressed on View > Tag mode off
Step result: tags are visible

2. Changed an entity type

3. Pressed on View > Tag mode on
Step result: tags are still visible

**Comment by ilovan** [comment]
never mind - working in dev 8.6

**Comment by Thaerious** [comment]
All future changes will be on 0.8.6, I keep the old ones around in case we need to see if something inadvertently broke during a fix or if it was already broken.
