### ISSUE TITLE
Date label still showing up for date tags, even if NERVE is no longer doing NER for dates

### ISSUE THREAD

**Issue by ilovan** [cwrc/NERVE#68]
![image.png](https://images.zenhubusercontent.com/5a5e621f4b5806bc2bc2ff7d/95f64973-f2ec-4623-a2de-de257e069942)

**Comment by Thaerious** [comment]
I need to know the exact behavior you want with date tags.  
- Do you want them to never show up?  In which case they get removed from the context.  Stanford is only tagging Location, Person, Organization.  Dates are included only if they are already tagged.  Removing them from the context will stop them from showing up.

**Comment by SusanBrown** [comment]
Yes, remove from the context, then, so they never get highlighted, labelled, etc. Thx



On Jun 21, 2018, at 10:15 AM, Ed Armstrong <notifications@github.com<mailto:notifications@github.com>> wrote:


I need to know the exact behavior you want with date tags.

  *   Do you want them to never show up? In which case they get removed from the context. Stanford is only tagging Location, Person, Organization. Dates are included only if they are already tagged. Removing them from the context will stop them from showing up.

**Comment by ilovan** [comment]
Fixed
