### ISSUE TITLE
Add level value to TITLE tags

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/NERVE#7]
Add default values to title tags, since a value is required by the schema, so texts with title tags inserted will otherwise be invalid.

CWRC schema: use allcaps MONOGRAPHIC as default value
`<TITLE LEVEL="MONOGRAPHIC">`

ORLANDO schema: use allcaps MONOGRAPHIC as default value
`<TITLE TITLETYPE="MONOGRAPHIC">`

TEI schema: use lower-case m as default value
`<TITLE LEVEL="m">`

**Comment by SusanBrown** [comment]
NB @Thaerious Realized there was a distinction between title tags in CWRC and Orlando schemas so revised the specifications.

**Comment by Thaerious** [comment]
Defaults have been added, I can't remember exactly when.  Working on special formatting next.
