### ISSUE TITLE
Save does not work for Orlando and CWRC documents

### ISSUE THREAD

**Issue by ilovan** [cwrc/NERVE#70]
1. Picked NER & Linking
2. Uploaded https://www.dropbox.com/s/hbsri6m5palutw3/NERVE_CWRC_entry_schema_test_entry_SHORT_NO_ENTITY_TAGS.xml?dl=0 or https://www.dropbox.com/s/6v4h39aog58c0yy/NERVE_Orlando_biography%20schema_test_entry_short_NO_entity_tags.xml?dl=0
3. Hit Save

Results:
All visual references to the tagging (highlights, label) disappears.

**Comment by Thaerious** [comment]
Now retains visual references.

**Comment by ilovan** [comment]
Confirmed that:

Visual references persist after clicking save
I was able to download CWRC and Orlando documents
