### ISSUE TITLE
Search does not work within the main document viewing pane

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/NERVE#71]
## Expected Behaviour
I would expect that if I clicked on this panel and then used the CtrlF functionality in my browser my browser search box would appear and I could search within the panel. This will be quite important for long docs.

## Current Behaviour
Seems to do nothing.

**Comment by Thaerious** [comment]
It's just disabled at the moment and will be put back in.  Note however, the find function in the browser can't be over-ridden with Javascript.  Research into it implies it requires a browser plug-in.  The search before didn't override your browser search, it implemented it's own.

**Comment by ilovan** [comment]
@Thaerious , browser search works with Git-Writer (try it yourself in one of the template documents @ cwrc-writer.cwrc.ca

Not sure how that was achieved, but I know for sure that it does not require any browser plug-in from the user. 
some details that may help are located here: https://github.com/cwrc/DEPRECATED-CWRC-Writer/issues/460
Let me know if you want me to set you up with Andrew for a conversation on how this can be achieved.

**Comment by Thaerious** [comment]
Search works the same as any web page.  Git-Writer doesn't override the search function.  For example, open the page, search for "Entities" the title in the tabbed pane is selected by the search.  Nerve has overridden the ctrl-f to search for Lemmas.  However, select "find" from the chrome menu and you will get the browser search.  Here you can type "name" and see what gets selected by the search, and why it needs to get overridden.

**Comment by Thaerious** [comment]
Search removed, you now have browser search only.
