### ISSUE TITLE
Issue with custom context where all tag names are identical

### ISSUE THREAD

**Issue by ajmacdonald** [cwrc/NERVE#83]
I'm working on support for using the [TEI rs tag](https://tei-c.org/release/doc/tei-p5-doc/en/html/ref-rs.html) to add named entities.

My context object looks like this:
```
{
    "name": "CUSTOM_RS_CONTEXT",
    "tags": {
        "PERSON": {
            "name": "rs",
            "lemmaAttribute": "key",
            "linkAttribute": "ref",
            "idAttribute": "id",
            "defaults": { "type": "http://sparql.cwrc.ca/ontologies/cwrc#PersonalName" }
        },
        "LOCATION": {
            "name": "rs",
            "lemmaAttribute": "key",
            "linkAttribute": "ref",
            "idAttribute": "id",
            "defaults": { "type": "http://sparql.cwrc.ca/ontologies/cwrc#Place" }
        },
        "ORGANIZATION": {
            "name": "rs",
            "lemmaAttribute": "key",
            "linkAttribute": "ref",
            "idAttribute": "id",
            "defaults": { "type": "http://www.w3.org/ns/org#FormalOrganization" }
        },
        "TITLE": {
            "name": "rs",
            "lemmaAttribute": "key",
            "linkAttribute": "ref",
            "idAttribute": "id",
            "defaults": { "type": "http://sparql.cwrc.ca/ontologies/cwrc#Title" }
        }
    }
}
```

As you can see, each entity uses the `rs` tag, and so uses the `type` attribute value to distinguish between them.

When I test this on a document, all tagged named entities end up being "person" (or whatever the first entry is in the context object).  When the tag name is unique for each entity type, then this problem doesn't occur.

**Comment by ajmacdonald** [comment]
@Thaerious does this seem like it would be a simple fix? If not I can come up with a workaround on my end.

**Comment by SusanBrown** [comment]
@Thaerious Andrew will go ahead with the workaround since this is outside of the scope of what we outlined.

**Comment by Thaerious** [comment]
The original ticket got buried so I missed the ticket.  I'll have a look at it, this is not a condition I anticipated.  A workaround may be best.

**Comment by jefferya** [comment]
@ilovan 
Untested fix for this issue. Don't have an easy way to verify.

**Comment by jefferya** [comment]
commit 8299f9c -- appears to fix the rs bug when custom context file provided like the attached.

A test file to for testing the following problems (contains the contents sent to NERVE by CWRC-Writer with a response expected from NERVE given a custom context file included in the request):
* lemmaAttribute: added
* rs: type attribute that differentiates entity type
* resp: 

```
curl -i -X POST -H "Content-Type: application/json"   -d @./test_documents/nerve_test_cwrc_tei_lite_custom_context_rs.json  https://gitwriter.services.cwrc.ca/nerve-uat/ner
```

[nerve_test_cwrc_tei_lite_custom_context_rs.txt](https://github.com/cwrc/NERVE/files/3976801/nerve_test_cwrc_tei_lite_custom_context_rs.txt)
